In [1]:
import numpy as np

row = np.array([1,2,3])
print(row)


[1 2 3]


In [5]:
a = np.array([(1,0,3),(0,5,6)], dtype='i8')
print(a)


print('This is a ',a.ndim,' dimensional array')
print('Each element is of type: ',a.dtype)
print('The size of this array is: ',a.size)
print('and its shape is: ', a.shape)


[[1 0 3]
 [0 5 6]]
This is a  2  dimensional array
Each element is of type:  int64
The size of this array is:  6
and its shape is:  (2, 3)


In [14]:
new_a = a.astype(bool)
print(new_a)
print('This is a ',new_a.ndim,' dimensional array')
print('Each element is of type: ',new_a.dtype)


[[ True False  True]
 [False  True  True]]
This is a  2  dimensional array
Each element is of type:  bool


In [15]:
a = np.array([(1.1,0,3),(0,5.8,6)],dtype='f8')
print(a)
print('This is a ',a.ndim,' dimensional array')
print('Each element is of type: ',a.dtype)
print('The size of this array is: ',a.size)
print('and its shape is: ', a.shape)


[[1.1 0.  3. ]
 [0.  5.8 6. ]]
This is a  2  dimensional array
Each element is of type:  float64
The size of this array is:  6
and its shape is:  (2, 3)


In [18]:
#new_a = a.astype(int)
new_a = a.astype('i2')
print(new_a)
print('This is a ',new_a.ndim,' dimensional array')
print('Each element is of type: ',new_a.dtype)


[[1 0 3]
 [0 5 6]]
This is a  2  dimensional array
Each element is of type:  int16


In [7]:
a=a.reshape(3,2)
print(a)
print('This is a ',a.ndim,' dimensional array')
print('Each element is of type: ',a.dtype)
print('The size of this array is: ',a.size)
print('and its shape is: ', a.shape)


[[1 0]
 [3 0]
 [5 6]]
This is a  2  dimensional array
Each element is of type:  int64
The size of this array is:  6
and its shape is:  (3, 2)


In [11]:
import sys
S= range(1000)
print('The size of this list is approximately: ',
      sys.getsizeof(5)*len(S))


The size of this list is approximately:  28000


1000

In [23]:
 
D= np.arange(1000)
print('The size of this array list is approximately: ',
      D.size*D.itemsize)


The size of this array list is approximately:  4000


In [24]:
print(np.arange(3))
print(np.arange(3.0))
print(np.arange(3,7))
print(np.arange(3,15,2))


[0 1 2]
[0. 1. 2.]
[3 4 5 6]
[ 3  5  7  9 11 13]


In [25]:
empty_array = np.zeros((3,4))
print(empty_array)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
ones_array = np.ones((3,4))
print(ones_array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
a = np.random.rand(3,4)
print(a)


[[0.94740578 0.69903466 0.18589817 0.08097752]
 [0.99237993 0.68992768 0.21378628 0.49574528]
 [0.45922866 0.11354516 0.76335588 0.26320036]]


In [28]:
a = np.array([(1, 0),(0,3)])
b = np.array([(3, 5),(1,7)])
print('a=\n',a)
print('b=\n',b)


a=
 [[1 0]
 [0 3]]
b=
 [[3 5]
 [1 7]]


In [29]:
print('a*b=\n',a*b)


a*b=
 [[ 3  0]
 [ 0 21]]


In [30]:
print('a@b=\n',a@b)

print('a.dot(b)=\n',a.dot(b))

print('np.dot(a,b)=\n',np.dot(a,b))



a@b=
 [[ 3  5]
 [ 3 21]]
a.dot(b)=
 [[ 3  5]
 [ 3 21]]
np.dot(a,b)=
 [[ 3  5]
 [ 3 21]]
